config/routes.rb
Rails.application.routes.draw do
  root "root#index"

  resource :setting, only: [:update]
  resources :procon_bypass_man_remote_single_commands, only: [:create]

  resources :procon_bypass_man_commands, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :remote_commands, only: [:create], module: :procon_bypass_man_commands
  end

  resources :procon_bypass_man_hosts, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :command_rules, only: [:update, :destroy]

  resources :captured_images, only: [:create]
end

app/models/procon_bypass_man_command.rb
class ProconBypassManCommand < ApplicationRecord
  validates :name, :first_buttons, presence: true
  validates :repeat_count, numericality: { greater_than_or_equal_to: 1 }
  # TODO: スペースは容認しつつ、カンマ区切りかつ、存在しないボタンをブロックするバリデーションを入れる

  # TODO: カラムの中身を, でsplitしたほうがいいかも
  def to_buttons_as_remote
    repeat_count.times.reduce([]){ |a, item|
      a.push(first_buttons)
      a.push(second_buttons) if second_buttons.present?
      next a
    }
  end
end

app/controllers/procon_bypass_man_commands/remote_commands_controller.rb
class ProconBypassManCommands::RemoteCommandsController < ApplicationController
  def create
    setting = Setting.instance

    if(procon_bypass_man_host = Setting.instance.procon_bypass_man_host).nil?
      render :bad_request
      return
    end

    ProconBypassManCommand.find(params[:procon_bypass_man_command_id]).to_buttons_as_remote.each do |buttons|
      command_response = procon_bypass_man_host.send_command(buttons: Array.wrap(buttons))
      Rails.logger.info { command_response } # TODO: commandとresponseを併記する
    end

    head :ok
  end
end

app/controllers/procon_bypass_man_commands_controller.rb
class ProconBypassManCommandsController < ApplicationController
  def index
    @procon_bypass_man_commands = ProconBypassManCommand.all
  end

  def new
    @procon_bypass_man_command = ProconBypassManCommand.new
  end

  def create
    @procon_bypass_man_command = ProconBypassManCommand.new(procon_bypass_man_command_params)

    if @procon_bypass_man_command.save
      redirect_to procon_bypass_man_commands_path, notice: 'ProconBypassManCommand was successfully created.'
    else
      render :new
    end
  end

  def edit
    @procon_bypass_man_command = ProconBypassManCommand.find(params[:id])
  end

  def update
    @procon_bypass_man_command = ProconBypassManCommand.find(params[:id])
    if @procon_bypass_man_command.update(procon_bypass_man_command_params)
      redirect_to procon_bypass_man_commands_path, notice: 'ProconBypassManCommand was successfully created.'
    else
      render :edit
    end
  end

  private

  def procon_bypass_man_command_params
    params.require(:procon_bypass_man_command).permit(:name, :first_buttons, :second_buttons, :repeat_count)
  end
end

app/views/procon_bypass_man_commands/_form.html.erb
<%= form_with(model: @procon_bypass_man_command, local: true) do |form| %>
  <% if @procon_bypass_man_command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procon_bypass_man_command.errors.count, "error") %> prohibited this procon_bypass_man_command from being saved:</h2>
      <ul>
        <% @procon_bypass_man_command.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :first_buttons %>
    <%= form.text_field :first_buttons %>
  </div>

  <div class="field">
    <%= form.label :second_buttons %>
    <%= form.text_field :second_buttons %>
  </div>


  <div class="field">
    <%= form.label :repeat_count %>
    <%= form.number_field :repeat_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/procon_bypass_man_commands/edit.html.erb
<h1>Edit ProconBypassManCommand</h1>

<%= render 'form' %>
<%= link_to 'Back', procon_bypass_man_commands_path %>

app/views/procon_bypass_man_commands/index.html.erb
<%= link_to '新規作成する', new_procon_bypass_man_command_path %>

<% if @procon_bypass_man_commands.empty? %>
  <p>procon_bypass_man_commandの登録がありません</p>
<% else %>
  <table border=1>
    <tr>
      <th>
        hostname
      </th>
      <th>
        first buttons
      </th>
      <th>
        seconds buttons
      </th>
      <th>
        repeat_count
      </th>
      <th></th>
      <th></th>
    </tr>

    <% @procon_bypass_man_commands.each do |procon_bypass_man_command| %>
      <tr>
        <td>
          <%= procon_bypass_man_command.name %>
        </td>
        <td>
          <%= procon_bypass_man_command.first_buttons %>
        </td>
        <td>
          <%= procon_bypass_man_command.second_buttons %>
        </td>
        <td>
          <%= procon_bypass_man_command.repeat_count %>
        </td>
        <td>
          <%= link_to 'edit', edit_procon_bypass_man_command_path(procon_bypass_man_command) %>
        </td>
        <td>
          <%= link_to 'テスト送信', procon_bypass_man_command_remote_commands_path(procon_bypass_man_command), method: :post, data: { remote: true } %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/procon_bypass_man_commands/new.html.erb
<h1>New ProconBypassManCommand</h1>

<%= render 'form' %>
<%= link_to 'Back', procon_bypass_man_commands_path %>