config/routes.rb
Rails.application.routes.draw do
  root "root#index"

  resource :setting, only: [:update]
  resources :procon_bypass_man_remote_single_commands, only: [:create]

  resources :procon_bypass_man_commands, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :remote_commands, only: [:create], module: :procon_bypass_man_commands
  end

  resources :procon_bypass_man_hosts, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :command_rules, only: [:update, :destroy]

  resources :captured_images, only: [:create]
end

app/models/procon_bypass_man_host.rb
class ProconBypassManHost < ApplicationRecord
  validates :name, :port, presence: true

  cattr_accessor :client_table

  def send_command(buttons: )
    Timeout.timeout(1) do
      client.send_command(buttons: buttons)
    end
  rescue IOError, Errno::EPIPE
    self.client_table[client_key] = nil
    Rails.logger.error { e }
    retry
  rescue Timeout::Error
    client&.close
    raise 'timeoutによって通信に失敗しました'
  end

  private

  # @return [ProconBypassManTcpClient]
  def client
    self.client_table ||= {}
    self.client_table[client_key] ||= ProconBypassManTcpClient.new(hostname: name, port: port)
  end

  def client_key
    [name, port].join
  end
end

app/controllers/procon_bypass_man_hosts_controller.rb
class ProconBypassManHostsController < ApplicationController
  def index
    @procon_bypass_man_hosts = ProconBypassManHost.all
  end

  def new
    @procon_bypass_man_host = ProconBypassManHost.new
  end

  def create
    @procon_bypass_man_host = ProconBypassManHost.new(procon_bypass_man_host_params)

    if @procon_bypass_man_host.save
      redirect_to procon_bypass_man_hosts_path, notice: 'Procon Bypass Man Host was successfully created.'
    else
      render :new
    end
  end

  def edit
    @procon_bypass_man_host = ProconBypassManHost.find(params[:id])
  end

  def update
    @procon_bypass_man_host = ProconBypassManHost.find(params[:id])
    if @procon_bypass_man_host.update(procon_bypass_man_host_params)
      redirect_to procon_bypass_man_hosts_path, notice: 'Procon Bypass Man Host was successfully created.'
    else
      render :edit
    end
  end

  private

  def procon_bypass_man_host_params
    params.require(:procon_bypass_man_host).permit(:name, :port, :note)
  end
end

app/views/procon_bypass_man_hosts/_form.html.erb
<%= form_with(model: @procon_bypass_man_host, local: true) do |form| %>
  <% if @procon_bypass_man_host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procon_bypass_man_host.errors.count, "error") %> prohibited this procon_bypass_man_host from being saved:</h2>
      <ul>
        <% @procon_bypass_man_host.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :port %>
    <%= form.number_field :port %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/procon_bypass_man_hosts/edit.html.erb
<h1>Edit Procon Bypass Man Host</h1>

<%= render 'form' %>
<%= link_to 'Back', procon_bypass_man_hosts_path %>

app/views/procon_bypass_man_hosts/index.html.erb
<%= link_to '新規作成する', new_procon_bypass_man_host_path %>

<% if @procon_bypass_man_hosts.empty? %>
  <p>procon_bypass_man_hostの登録がありません</p>
<% else %>
  <table border=1>
    <tr>
      <th>
        hostname
      </th>
      <th>
        port
      </th>
      <th>
        note
      </th>
      <th></th>
    </tr>

    <% @procon_bypass_man_hosts.each do |procon_bypass_man_host| %>
      <tr>
        <td>
          <%= procon_bypass_man_host.name %>
        </td>
        <td>
          <%= procon_bypass_man_host.port %>
        </td>
        <td>
          <%= simple_format procon_bypass_man_host.note %>
        </td>
        <td>
          <%= link_to 'edit', edit_procon_bypass_man_host_path(procon_bypass_man_host) %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/procon_bypass_man_hosts/new.html.erb
<h1>New ProconBypassManHost</h1>

<%= render 'form' %>
<%= link_to 'Back', procon_bypass_man_hosts_path %>