config/routes.rb
Rails.application.routes.draw do
  root "root#index"

  resource :setting, only: [:update]
  resources :procon_bypass_man_remote_single_commands, only: [:create]

  resources :procon_bypass_man_commands, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :remote_commands, only: [:create], module: :procon_bypass_man_commands
  end

  resources :procon_bypass_man_hosts, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :command_rules, only: [:update, :destroy]

  resources :captured_images, only: [:create]
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @setting = Setting.instance
  end
end

app/views/root/index.html.erb
<% if ProconBypassManHost.all.empty? %>
  <p>
    ProconBypassManHostの登録がありません。ProconBypassManHostを登録してください。
  </p>
<% end %>

<% if @setting.capture_device_name.blank? %>
  <p>
    キャプチャデバイスのインデックス番号が未登録です。登録してください。
  </p>
<% end %>

<p>
  <%= form_with(model: @setting, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <div class="field">
      <%= form.label :capture_device_name, 'キャプチャデバイスのインデックス番号' %>
      <%= form.text_field :capture_device_name %>
    </div>
    <div class="actions">
      <%= form.submit '保存' %>
    </div>
  <% end %>
</p>

<p>
  <%= form_with(model: @setting, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <div class="field">
      <%= form.label :procon_bypass_man_host_id, '送信先PBM' %>
      <%= form.select :procon_bypass_man_host_id, ProconBypassManHost.all.collect { |host| [host.name, host.id] }, { prompt: 'Select a ProconBypassManHost' } %>
    </div>
    <div class="actions">
      <%= form.submit '保存' %>
    </div>
  <% end %>
</p>

<p>
  <%= form_with(model: @setting, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <div class="field">
      <%= form.hidden_field :capture_enabled, value: !@setting.capture_enabled %>
    </div>
    <div class="actions">
      <% if @setting.capture_enabled %>
        <div class="submit-loader-wrapper">
          <div class='loader'></div>
          <%= form.submit '⏸️ 画面キャプチャと画像解析を停止する' %>
        </div>
      <% else %>
        <div class="submit-loader-wrapper">
          <div class='stopped-loader'></div>
          <%= form.submit '▶️ 画面キャプチャと画像解析を開始する' %>
        </div>
      <% end %>
    </div>
  <% end %>
</p>


<h3>動作確認</h3>

<ul>
  <li>PBMへ入力を行う</li>
  <!--
  <ul>
    <li>
      <div style='display: none'>
        <%= Procon::BUTTONS.map { |x| link_to(x, procon_bypass_man_remote_single_commands_path(buttons: [x], format: :js), class: 'button-like', data: { remote: true, remote_single_command: x }, method: :post) }.join.html_safe %>
      </div>
      <div data-controller='single-commander-procon'></div>
    </li>
    <li>
      結果: <span id='single-command-result'></span>
    </li>
  </ul>
  -->
  <ul>
    <li>
    <%= Procon::BUTTONS.map { |x| link_to(x, procon_bypass_man_remote_single_commands_path(buttons: [x], format: :js), class: 'button-like', data: { remote: true, remote_single_command: x }, method: :post) }.join.html_safe %>
    </il>
  </ul>
  <li><%= link_to '画面キャプチャを行う', captured_images_path, method: :post, data: { remote: true } %></li>
  <ul>
    <li>
      <img id="captured-image" style='max-height: 300px' />
      <div id="captured-image-log"></div>
    </li>
  </ul>
</ul>